### ISSUE TITLE
Cleanup deprecated API usage

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/suitcase-core#48]
This line should be fixed:

https://github.com/NSLS-II/suitcase/blob/master/suitcase/hdf5.py#L96

This will call another instance of databroker which is deprecated.

Should also probably consider removing this global instance overall, as @tacaswell suggested.

In this case, `export` wasn't working properly at LIX because the proper file handler to read the data was not registered for this unused instance.

**Comment by tacaswell** [comment]
This is likely fixed by #44

**Comment by jrmlhermitte** [comment]
That would fix it. Thanks! I'll review code later

**Comment by danielballan** [comment]
No longer relevant now that the module in question is blown away (still in git history though).
